apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: awss3buckets.crossplane.hansemerkur.de
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: crossplane.hansemerkur.de/v1alpha1
    kind: x-awss3bucket
  resources:
    - name: awss3bucket_1
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            region: eu-central-1
      patches:
       - fromFieldPath: "spec.parameters.bucketName"
         toFieldPath: "metadata.name"
       - fromFieldPath: "spec.parameters.region"
         toFieldPath: "spec.forProvider.region"
